# Generated by Django 4.2.4 on 2023-08-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_customer',
            new_name='is_employee',
        ),
    ]
