# Generated by Django 4.2.4 on 2023-08-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_customer_employee_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
